SELECT HACL.HSP_ACCOUNT_ID AS ACCTNO,
         VACL.BENEFIT_PLAN_ID,
         BENEFIT_PLAN_NAME,
         VACL.COVERAGE_ID,
         HACL.LINE,
         CVG.PLAN_GRP_ID CVG.SUBSCR_EMPLOYER_ID,
         CVG.SUBSCR_NUM,
         CVG.GROUP_NUM,
         CVG3.AUTH_NUM,
         har.tot_pmts AS payment_amount,
         har.ACCT_FIN_CLASS_C,
        
FROM dbo.hsp_account har
INNER JOIN DBO.HSP_ACCT_CVG_LIST HACL
    ON har.HSP_ACCOUNT_ID = hacl.HSP_ACCOUNT_ID
LEFT JOIN DBO.V_COVERAGE_PAYOR_PLAN VCPL
    ON HACL.COVERAGE_ID = VCPL.COVERAGE_ID
LEFT JOIN DBO.COVERAGE CVG
    ON HACL.COVERAGE_ID = CVG.COVERAGE_ID
LEFT JOIN DBO.COVERAGE CVG3
    ON CVG.COVERAGE_ID = CVG3.COVERAGE_ID
LEFT JOIN dbo.zc_financial_class zfc
    ON har.ACCT_FIN_CLASS_C = zfc.FINANCIAL_CLASS -- F_ARHB_HAR_SNAPSHOT